### ISSUE TITLE
Provide a way to develop the dependency locally easily

### ISSUE THREAD

**Issue by SerVB** [korlibs/kotlin-source-dependency-gradle-plugin#1]
When using traditional dependencies in a project, I can easily develop the project and the dependency at the same time. There are two ways, actually:
1. I can publish changed dependency to Maven Local.
2. I can [substitute a module of a Gradle project as a dependency](https://github.com/JetBrains/projector-server/blob/7ec3cbfc14ff0ca38f80699fc067d6fa9acd1364/settings.gradle.kts#L24-L32).

With kotlin-source-dependency-gradle-plugin, it's not clear for me how to develop the dependency and the project at the same time: it seems I have to push the dependency and only after it I can use the updated dependency in the main project.

Is there a way? If not, probably a similar substitution mechanism can be implemented.

**Comment by soywiz** [comment]
Makes sense. Being able to work with development libraries is something that worked extremely well with maven for example by being convention-based. Let's try to figure out a way to do this properly.

**Comment by soywiz** [comment]
Replaced by kproject https://github.com/korlibs/kproject
with kproject this problem is fixed by using local paths for dependencies
