### ISSUE TITLE
Add dependencies of source dependencies to the dependencies of the module

### ISSUE THREAD

**Issue by SerVB** [korlibs/kotlin-source-dependency-gradle-plugin#2]
A mechanism to add dependencies of dependencies is needed. I think it can be default behavior but a way of disabling not needed dependencies is needed. By default, Kotlin stdlib can be disabled (because it's probably already persists in the module and we don't want conflicts when the dependency uses 1.4.21 and the module uses 1.4.30).

Currently, it's needed to copy dependencies declarations manually.

**Comment by soywiz** [comment]
https://github.com/korlibs/kproject this problem is also solved
