### ISSUE TITLE
`embedded-kotlin` and `kotlin-dsl` plugin versions

### ISSUE THREAD

**Issue by airxnoor** [korlibs/kotlin-source-dependency-gradle-plugin#3]
This plugin uses an older version of Kotlin (1.4.21) and trying to use it produces a warning which causes the build to stop:

```
> Configure project :buildSrc
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.5.31` that might work differently than in the requested version `1.4.21`.
```

Any way to circumvent this somehow while still using the plugin as-is?

**Comment by soywiz** [comment]
This was fixed already on the `main` branch
